<x-app-layout>
    <div class="container px-4 mt-4">
        @if(session('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
        @if (auth()->user()->role == 'superadmin')
            <div class="d-flex justify-content-between">
                <p class="ms-4 fw-bold f-16">Clients</p>
                <a href="{{ route('superadmin.inviteCompany')}}" class="mr-4 btn btn-sm bg-primary text-light">Invite Client</a>
            </div>
            <div class="content-area">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Client Name</th>
                            <th>Users</th>
                            <th>Total Generated URLs</th>
                            <th>Total URLs Hits</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($companies)) 
                        @foreach ($companies as $company)
                            <tr>
                                <td>{{$company->name}}</td>
                                <td>{{count($company->users)}}</td>
                                <td>{{ $company->short_urls_count ?? 0 }}</td>
                                <td>{{ $company->short_urls_count ?? 0}}</td>
                            </tr> 
                        @endforeach
                        @endif   
                    </tbody>
                </table>
            </div>
        @endif
        @if (in_array(auth()->user()->role, ['admin', 'member', 'sales', 'manager']))
            <div class="d-flex justify-content-between my-3">
                <p class="ms-4 fw-bold f-16">Generated Short Urls</p>
                <div>
                    <a href="{{ route('admin.generateUrl')}}" class="me-4 btn btn-sm bg-primary text-light">Generate</a>
                    <select name="short_url" id="" class="me-4">
                        <option value="">Last Month</option>
                        <option value="">Last Week</option>
                        <option value="">Today</option>
                    </select>
                    <a href="{{ route('admin.downloadUrls')}}" class="me-4 btn btn-sm bg-primary text-light">Dowanload</a>
                </div>
            </div>
            <div class="content-area mb-4">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Short Url</th>
                            <th>Long Url</th>
                            <th>Hits</th>
                            <th>Generated By</th>
                            <th>Created On</th>
                        </tr>
                        @if ($shortUrls)
                            @foreach ($shortUrls as $url)
                                <tr>
                                    <td>{{$url->short_code ?? 'N/A'}}</td>
                                    <td>{{$url->original_url ?? 'N/A'}}</td>
                                    <td>{{$url->hits ?? 0}}</td>
                                    <td>{{$url->user->name ?? 'N/A'}}</td>
                                    <td>{{$url->created_at ?? 'N/A'}}</td>
                                </tr>
                            @endforeach
                        @endif
                    </thead>
                </table>
            </div>
        @endif
        @if (auth()->user()->role == 'admin')
            <div class="d-flex justify-content-between mt-4 mb-2">
                <p class="ms-4 fw-bold">Clients</p>
                <a href="{{ route('admin.inviteTeamMember')}}" class="me-4 btn btn-sm bg-primary text-light">Invite Member</a>
            </div>
            <div class="content-area">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Total Generated URLs</th>
                            <th>Total URLs Hits</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($users)) 
                        @foreach ($users as $user)
                            <tr>
                                <td>{{$user->name ?? 'N/A'}}</td>
                                <td>{{$user->email ?? 'N/A'}}</td>
                                <td>{{ $user->short_urls_count ?? 0 }}</td>
                                <td>{{ $user->short_urls_sum_hits ?? 0}}</td>
                            </tr> 
                        @endforeach
                        @endif   
                    </tbody>
                </table>
            </div>
        @endif  
    </div>
</x-app-layout>
