<x-app-layout>
    <div class="container px-4 mt-4">
        @if(session('message'))
            <div class="alert alert-success">
                {{ session('message') }}
            </div>
        @endif
        @if (auth()->user()->role == 'superadmin')
            <div class="d-flex justify-content-between">
                <p class="ms-4 fw-bold f-16">Clients</p>
                <a href="{{ route('superadmin.inviteCompany')}}" class="mr-4 btn btn-sm bg-primary text-light">Invite Client</a>
            </div>
            <div class="content-area">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Client Name</th>
                            <th>Users</th>
                            <th>Total Generated URLs</th>
                            <th>Total URLs Hits</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($companies)) 
                        @foreach ($companies as $company)
                            <tr>
                                <td>{{$company->name}}</td>
                                <td>{{count($company->users)}}</td>
                                <td>{{count($company->shortUrls) ?? 0 }}</td>
                                <td>{{$company->short_urls_sum_hits ?? 0}}</td>
                            </tr> 
                        @endforeach
                        @endif   
                    </tbody>
                </table>
                @if(isset($companies))
                    <div class="mt-3">
                        {{ $companies->links() }}
                    </div>
                @endif
            </div>
        @endif
        @if (in_array(auth()->user()->role, ['admin', 'member', 'sales', 'manager', 'superadmin']))
            <div class="d-flex justify-content-between my-3">
                <p class="ms-4 fw-bold f-16">Generated Short Urls</p>
                <div>
                    @if (auth()->user()->role !== 'superadmin')
                    <a href="{{ route('admin.generateUrl')}}" class="me-4 btn btn-sm bg-primary text-light">Generate</a>
                    @endif
                    <form method="GET" action="{{ route('dashboard') }}" class="d-inline">
                        <select name="sort_by_date" class="me-4" onchange="this.form.submit()">
                            <option value="" {{ request('sort_by_date') === null || request('sort_by_date') === '' ? 'selected' : '' }}>All</option>
                            <option value="last_month" {{ request('sort_by_date') === 'last_month' ? 'selected' : '' }}>Last Month</option>
                            <option value="last_week" {{ request('sort_by_date') === 'last_week' ? 'selected' : '' }}>Last Week</option>
                            <option value="today" {{ request('sort_by_date') === 'today' ? 'selected' : '' }}>Today</option>
                        </select>
                    </form>
                    <a href="{{ route('admin.downloadUrls', ['sort_by_date' => request('sort_by_date')]) }}" class="me-4 btn btn-sm bg-primary text-light">Dowanload</a>
                </div>
            </div>
            <div class="content-area mb-4">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Short Url</th>
                            <th>Long Url</th>
                            <th>Hits</th>
                            <th>Generated By</th>
                            <th>Created On</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($shortUrls)
                            @foreach ($shortUrls as $url)
                                <tr>
                                    <td>{{$url->short_code ?? 'N/A'}}</td>
                                    <td>{{$url->original_url ?? 'N/A'}}</td>
                                    <td>{{$url->hits ?? 0}}</td>
                                    <td>{{$url->user->name ?? 'N/A'}}</td>
                                    <td>
                                        {{$url->created_at ?? 'N/A'}}
                                    <a href="{{ route('shorturl.open', $url->short_code) }}" target="_blank" class="btn btn-primary btn-sm ms-1">Visit</a>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
                @if(isset($shortUrls))
                    <div class="mt-3">
                        {{ $shortUrls->links() }}
                    </div>
                @endif
            </div>
        @endif
        @if (auth()->user()->role == 'admin')
            <div class="d-flex justify-content-between mt-4 mb-2">
                <p class="ms-4 fw-bold">Clients</p>
                <a href="{{ route('admin.inviteTeamMember')}}" class="me-4 btn btn-sm bg-primary text-light">Invite Member</a>
            </div>
            <div class="content-area">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Total Generated URLs</th>
                            <th>Total URLs Hits</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(isset($users)) 
                        @foreach ($users as $user)
                            <tr>
                                <td>{{$user->name ?? 'N/A'}}</td>
                                <td>{{$user->email ?? 'N/A'}}</td>
                                <td>{{ $user->short_urls_count ?? 0 }}</td>
                                <td>{{ $user->short_urls_sum_hits ?? 0}}</td>
                            </tr> 
                        @endforeach
                        @endif   
                    </tbody>
                </table>
                @if(isset($users))
                    <div class="mt-3">
                        {{ $users->links() }}
                    </div>
                @endif
            </div>
        @endif  
    </div>
</x-app-layout>
